// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"live-pilot/api/handlers"
	"live-pilot/api/routes"
	"live-pilot/pkg/conf"
	"live-pilot/pkg/middleware"
	"live-pilot/pkg/repository"
	"live-pilot/pkg/service"
)

import (
	_ "live-pilot/docs"
)

// Injectors from wire.go:

func wireApp(appConfig conf.AppConfig) (*FiberApp, func(), error) {
	loggerConfig := middleware.NewLogger(appConfig)
	repositoryRepository, cleanup, err := repository.NewRepository(appConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	userRoutes := routes.NewUserRoutes(userHandler)
	v := routes.ProvideRoutes(userRoutes)
	fiberApp := newFiberApp(loggerConfig, v)
	return fiberApp, func() {
		cleanup()
	}, nil
}
