basePath: /api
host: 127.0.0.1:8000
info:
  contact: {}
  description: This is an API for Live
  title: LivePoliot
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get user details by user ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Get user by ID
      tags:
      - user
swagger: "2.0"
